#index:
#    path: /
#    controller: App\Controller\DefaultController::index

displayMusic:
  path: /displayMusic/{musicId}
  controller: App\Controller\MusicboxController::displayMusic
  requirements:
    id: '\d+'
